name: Testtest

on:
  workflow_dispatch:

jobs:
  jobjob:
    runs-on: self-hosted
    
    steps:
      - name: Hello world action step
        id: hello
        uses: socar-mackey/action-a
        with:
          who-to-greet: 'Mackey'
