name: Deploy Project

on:
  workflow_dispatch:
    inputs:
      target:
        description: "앱 타겟 (Socar/PairingOwner)"
        required: true
        default: "Socar"
        
      version:
        description: "앱 버전 (Major.Minor.Patch)"
        required: true
        default: "1.0.0"
        
      build:
        description: "빌드 번호"
        required: true
        default: "1234"        

      git:
        description: "변경 사항 push 여부"
        required: false
        default: "true"
      
      appstore:
        description: "앱스토어 업로드"
        required: true
        default: "true"

# 환경변수 설정
env:
  TARGET: ${{ github.event.inputs.target }}
  VERSION: ${{ github.event.inputs.version }}
  BUILD: ${{ github.event.inputs.build }}
  GIT: ${{ github.event.inputs.git }}
  APPSTORE: ${{ github.event.inputs.appstore }}

jobs:
  # 배포
  deploy:
    runs-on: self-hosted
    
    steps:
      # 배포 브랜치 체크아웃
      - name: Checkout
        run: |
          echo good1
        
      - name: Fastlane Deploy
        id: deployAdhoc
        if: ${{ success() }}
        run: |
          echo good2
          
      # 배포 변경사항 깃 푸시
      - name: Git push
        if: ${{ env.GIT == 'true' && steps.deployAdhoc.conclusion == 'success' }}
        continue-on-error: true
        run: |
          echo good3
          exit 1
          
      # 릴리즈 빌드 앱스토어 배포
      - name: Appstore Deploy
        if: ${{ env.APPSTORE == 'true' && steps.deployAdhoc.conclusion == 'success' }}
        run: |
          echo good4
