name: github-action-test

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  workflow_dispatch:
  
jobs:
  my_first_job:
    name: My First Job
    runs-on: self-hosted
    steps:
      - name: 1
        run: ls asjdflajsdlkf
      - name: 2
        if: ${{ success() }}
        run: echo good
